FROM node:24.14.1-alpine3.23

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true

COPY apps/redirector/package*.json ./

RUN npm ci

COPY apps/redirector/ ./

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
